version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
        
  employee-service:
    image: dockerdungeon/microservices1.0:latest
    ports:
    - 8010:8010
    links:
    - mongo

  zuul-server:
    image: dockerdungeon/zuulservice1.0:latest
    ports:
    - 8090:8090

  eureka-server:
    image: dockerdungeon/eurekaservice1.0:latest
    ports:
    - 8001:8001